@extends('layouts.legal')
@section('title', 'Política de privacidad — Okanet Solutions')
@section('description', 'Información sobre el tratamiento de datos personales, el contacto por WhatsApp y los derechos de privacidad en el sitio de Okanet Solutions.')
@section('legal-title', 'Política de privacidad')
@section('legal-content')
    <p>Esta política describe el tratamiento de datos en el sitio informativo de Okanet Solutions C.A., empresa establecida en Venezuela y sujeta a la legislación venezolana. Actualmente no tenemos clientes en la Unión Europea. Esto no excluye la aplicación de otras normas cuando se cumplan sus criterios territoriales; el RGPD puede resultar aplicable, por ejemplo, al dirigir servicios a personas en la Unión o monitorizar allí su comportamiento. Los productos OkaISP y OkaStore y los servicios contratados requieren sus propias condiciones e información sobre el tratamiento de datos.</p>
    <h2>1. Responsable y contacto</h2>
    <p>El titular del sitio es <strong>Okanet Solutions C.A., RIF J-41299500-6</strong>, con dirección en Av. Rómulo Gallegos con Calle Pedro Manrique, Edif. Centro ALOA, PP-36-L, Caracas 1071, Venezuela.</p>
    <p>Puedes dirigir consultas o solicitudes sobre tus datos a <a href="mailto:info@okanetsolutions.com">info@okanetsolutions.com</a>, escribir a la dirección anterior o llamar al <a href="tel:+584241780659">+58 424 178 0659</a>. No necesitas utilizar WhatsApp para ejercer tus derechos.</p>
    <h2>2. Qué datos se tratan</h2>
    <ul>
        <li>
            <strong>Navegación:</strong> el servidor recibe datos técnicos como la dirección IP, la URL solicitada y la información del navegador. Las sesiones pueden conservar la IP, el agente del navegador y la última actividad; el registro adicional depende de la infraestructura de alojamiento.</li>
        <li>
            <strong>Consultas:</strong> nombre, empresa si la indicas, servicio de interés y contenido del mensaje. Al escribir aquí y preparar el mensaje, los datos permanecen en la página de tu navegador; este formulario no los envía a una base de datos del sitio ni utiliza almacenamiento local.</li>
        <li>
            <strong>WhatsApp:</strong> si eliges continuar, el texto preparado se transmite a WhatsApp para abrir la conversación. Al enviarlo allí, Okanet recibe el mensaje y los datos de tu cuenta que WhatsApp comparte, como tu número y nombre de perfil.</li>
        <li>
            <strong>Administración:</strong> las personas autorizadas utilizan una cuenta con correo y contraseña. La aplicación mantiene la sesión y una cookie de acceso persistente al iniciar sesión.</li>
        <li>
            <strong>Notificaciones operativas:</strong> al registrarte o completar una acción que modifica datos, enviamos al responsable un aviso con tu nombre y correo si has iniciado sesión, la acción realizada, la ruta, la fecha y hora y la dirección IP. No incluimos contraseñas, tokens ni el contenido de los formularios.</li>
    </ul>
    <p>Los campos de empresa y mensaje son opcionales. El nombre se solicita para preparar el mensaje; puedes llamar o abrir WhatsApp directamente si no deseas utilizar el formulario. No envíes categorías especiales de datos, credenciales ni información confidencial.</p>
    <h2>3. Finalidades y bases jurídicas</h2>
    <p><strong>Cuenta y evaluaciones de ciberseguridad:</strong> guardamos tu nombre, correo corporativo, contraseña protegida mediante hash y fecha de verificación. Solo después de verificar el correo puedes solicitar consultas. Para la consulta de filtraciones enviamos tu correo a Breachsense; guardamos el número de registros encontrados y la fecha, sin almacenar las contraseñas o credenciales filtradas. Breachsense procesa la consulta conforme al servicio contratado; consulta su <a href="https://www.breachsense.com/privacy-policy/" rel="noreferrer">política de privacidad</a>.</p>
    <p>Para evaluar un dominio guardamos el dominio, el desafío DNS, su verificación y la autorización: identidad declarada del representante, correo verificado, IP, fecha, versión y alcance aceptado. Conservamos el estado de la solicitud, el resumen y el PDF del informe en almacenamiento privado. El cliente solo puede consultar sus propios informes entregados; el personal autorizado gestiona las evaluaciones. Enviamos correos de verificación, recuperación de acceso y disponibilidad de informes, sin adjuntar hallazgos al aviso.</p>
    <p>Las acciones «Solicitar más información» y «Solicitar informe completo» registran tu petición de contacto sobre los hallazgos y servicios de seguridad. Estas solicitudes y sus informes preliminares se gestionan como consultas de servicios conforme a los plazos de la sección 5, sin añadir una suscripción publicitaria. Puedes solicitar la eliminación de tu cuenta o la suspensión de una evaluación mediante nuestro correo de contacto. La autorización de pruebas se conserva según las obligaciones y reclamaciones aplicables.</p>
    <p>Tratamos los datos para responder consultas, preparar y ejecutar los servicios solicitados, administrar el sitio, protegerlo frente a abusos y cumplir las obligaciones legales venezolanas. No utilizamos los mensajes de consulta para fines ajenos a esa relación. Cuando sea aplicable el Reglamento General de Protección de Datos (RGPD), las bases jurídicas previstas son:</p>
    <ul>
        <li>
            <strong>Atender una solicitud de servicios:</strong> medidas precontractuales solicitadas por la persona interesada (artículo 6.1.b); para consultas de representantes de empresas y otras comunicaciones, el interés legítimo en gestionar la relación profesional (artículo 6.1.f), sujeto a la ponderación correspondiente.</li>
        <li>
            <strong>Operar y proteger el sitio:</strong> interés legítimo en mantener el servicio, controlar los accesos y prevenir incidentes (artículo 6.1.f).</li>
        <li>
            <strong>Cumplir obligaciones legales aplicables:</strong> cuando el tratamiento sea necesario conforme al artículo 6.1.c y a la legislación pertinente.</li>
    </ul>
    <p>El sitio no incorpora suscripciones comerciales, píxeles publicitarios ni analítica de comportamiento. Enviar una consulta no te suscribe a publicidad. Si se incorporan tratamientos opcionales basados en consentimiento, se solicitará por separado antes de iniciarlos.</p>
    <h2>4. Proveedores y tratamiento internacional</h2>
    <p>Okanet está en Venezuela y atiende las consultas desde ese país. Utilizamos los siguientes proveedores:</p>
    <ul>
        <li><strong>DigitalOcean:</strong> alojamiento del sitio y de los datos técnicos necesarios para su funcionamiento. El alojamiento principal está en NYC1 (Nueva York, Estados Unidos). Esta ubicación no determina la localización de los servicios de Cloudflare ni la de las copias que se almacenen en otros proveedores. Consulta su <a href="https://www.digitalocean.com/legal/data-processing-agreement" rel="noreferrer">acuerdo de tratamiento de datos</a>.</li>
        <li><strong>Cloudflare (DNS y proxy):</strong> resolución de nombres, distribución de contenido y protección del tráfico mediante el proxy estándar de Cloudflare. Estas funciones pueden tratar direcciones IP, solicitudes y datos de seguridad en su red internacional. Cloudflare indica que determinados datos de cookies pueden tratarse en Estados Unidos por defecto; la localización depende de los servicios contratados y su configuración. Consulta su <a href="https://www.cloudflare.com/privacypolicy/" rel="noreferrer">política de privacidad</a> y su <a href="https://www.cloudflare.com/cloudflare-customer-dpa/" rel="noreferrer">acuerdo de tratamiento</a>.</li>
        <li><strong>Cloudflare R2:</strong> almacenamiento de objetos y archivos. Los datos personales contenidos en esos archivos están sujetos a la finalidad y al plazo de conservación de cada categoría. La ubicación depende de la configuración del bucket de R2; no se garantiza una residencia exclusiva en NYC1 ni en un país concreto. Las indicaciones de ubicación son orientativas, mientras que las restricciones de jurisdicción son una configuración distinta. Consulta la <a href="https://developers.cloudflare.com/r2/reference/data-location/" rel="noreferrer">información sobre ubicación de datos en R2</a>.</li>
        <li><strong>Postmark:</strong> proveedor de procesamiento y entrega de correo electrónico. Puede tratar remitentes, destinatarios, contenido, adjuntos y datos de entrega en los mensajes que pasan por su servicio, con tratamiento internacional que puede incluir Estados Unidos. Consulta su <a href="https://postmarkapp.com/privacy-policy" rel="noreferrer">política de privacidad</a>. Su servicio de mensajería no debe confundirse con un archivo permanente de las comunicaciones.</li>
        <li><strong>WhatsApp (Meta):</strong> canal de contacto que solo se abre cuando lo eliges. Recibe el texto preparado al continuar hacia su servicio y aplica su <a href="https://www.whatsapp.com/legal/privacy-policy" rel="noreferrer">política de privacidad</a>.</li>
    </ul>
    <p>Escribir por correo también implica el tratamiento del mensaje por los proveedores que intervienen en su envío y recepción. Puedes contactar con Okanet en <a href="mailto:info@okanetsolutions.com">info@okanetsolutions.com</a> sin utilizar WhatsApp.</p>
    <p>El alojamiento y los servicios de red pueden implicar tratamiento fuera de Venezuela. No afirmamos que los datos permanezcan exclusivamente en Venezuela ni en la Unión Europea. Los proveedores actúan conforme a los servicios contratados y sus acuerdos de tratamiento. Puedes solicitar información sobre los destinatarios y las garantías aplicables a tus datos mediante nuestro correo de contacto. Los documentos enlazados describen las condiciones de los proveedores; no certifican por sí solos la configuración ni el cumplimiento de Okanet.</p>
    <p>Cuando el RGPD lo exija, las transferencias deberán contar con un mecanismo válido y con información sobre cómo obtener una copia de sus garantías. Visitar el sitio no constituye consentimiento general para transferencias internacionales.</p>
    <h2>5. Conservación</h2>
    <p>El mensaje preparado no se almacena por esta página. Los datos enviados por WhatsApp, correo o teléfono pasan a formar parte de la gestión de la consulta.</p>
    <p><strong>Plazos de conservación aprobados por Okanet:</strong> se aplican como política a los datos bajo nuestro control, con las excepciones legales y los plazos de proveedores que se indican a continuación. Su aprobación no significa que la eliminación automática esté activada en todos los sistemas.</p>
    <ul>
        <li><strong>Consultas sin contratación y sin obligación legal de archivo:</strong> eliminar o anonimizar a los 12 meses desde la última interacción. Revisar antes si el mensaje constituye correspondencia mercantil que deba conservarse.</li>
        <li><strong>Registros técnicos rutinarios bajo control de Okanet:</strong> conservar durante 30 días desde su generación y después eliminar o anonimizar. Los registros vinculados a un incidente o reclamación deben separarse, limitarse a lo necesario y revisarse hasta cerrar el caso y cumplir las obligaciones aplicables.</li>
        <li><strong>Copias de seguridad operativas bajo control de Okanet:</strong> rotación de 30 días desde la creación de cada copia. Tras eliminar datos del sistema activo, pueden permanecer en las copias hasta vencer ese ciclo. Si se restaura una copia, deben reaplicarse las eliminaciones antes de reutilizar esos datos.</li>
        <li><strong>Libros, comprobantes y correspondencia mercantil:</strong> el artículo 44 del Código de Comercio venezolano exige diez años de conservación; para los libros y sus comprobantes, el cómputo parte del último asiento de cada libro. La clasificación de mensajes, contratos y documentos fiscales y cualquier obligación adicional deben validarse con el asesor contable o jurídico. Estos archivos legales se conservan separados de las copias operativas de 30 días.</li>
    </ul>
    <p>Referencia: <a href="https://www.wipo.int/wipolex/es/legislation/details/4008" rel="noreferrer">Código de Comercio venezolano, artículo 44 (WIPO Lex)</a>. Ningún plazo de esta política autoriza a destruir datos sujetos a una obligación legal, orden de conservación o reclamación vigente.</p>
    <p>La eliminación o anonimización requiere aplicar estos plazos en los registros, archivos, copias y conversaciones correspondientes. Los archivos sujetos a conservación legal o a una reclamación deben mantenerse separados y con acceso limitado. La rotación de copias operativas no debe aplicarse indiscriminadamente a todos los objetos de R2 ni eliminar archivos comerciales que deban conservarse. La aprobación de estos plazos no acredita su ejecución en producción; las configuraciones de limpieza y su cumplimiento siguen pendientes de verificación. Las cookies tienen los plazos indicados en la <a href="{{ route('cookies') }}" wire:navigate>política de cookies</a>; su caducidad no elimina por sí sola los registros del servidor.</p>
    <p><strong>Conservación propia de Postmark:</strong> según su documentación, el contenido, los eventos y los metadatos de los mensajes se conservan por defecto durante 45 días; el plazo puede ajustarse mediante su complemento de retención. No se ha verificado un plazo personalizado en nuestra cuenta. Postmark también mantiene estadísticas agregadas y registros de supresión para determinados rebotes y reclamaciones. Estos datos no están sujetos a la rotación de 30 días de los registros locales de Okanet. Consulta los <a href="https://postmarkapp.com/support/article/how-long-are-inbound-and-outbound-messages-stored-in-activity" rel="noreferrer">plazos publicados por Postmark</a>.</p>
    <p>La eliminación de objetos de R2 mediante reglas de ciclo de vida es asíncrona y puede completarse después de la fecha de vencimiento. Cloudflare indica que normalmente ocurre dentro de las 24 horas siguientes, aunque puede tardar más. El objetivo aprobado de rotación de copias es de 30 días; no implica una garantía de borrado instantáneo. Consulta los <a href="https://developers.cloudflare.com/r2/buckets/object-lifecycles/" rel="noreferrer">ciclos de vida de objetos de R2</a>.</p>
    <h2>6. Tus derechos</h2>
    <p>Puedes escribir a <a href="mailto:info@okanetsolutions.com">info@okanetsolutions.com</a> para conocer qué datos tratamos y con qué finalidad, y solicitar su actualización, rectificación o eliminación conforme a la legislación aplicable. Cuando corresponda conforme al RGPD, también puedes ejercer los derechos de limitación, portabilidad y oposición al tratamiento. Puedes retirar cualquier consentimiento que hayas otorgado con la misma facilidad con la que lo diste, sin afectar al tratamiento lícito previo.</p>
    <p>Dirige la solicitud al responsable por los canales de la sección 1, indicando el derecho que deseas ejercer. Solo se debe pedir información adicional de identidad cuando resulte necesaria. El plazo general de respuesta bajo el RGPD es de un mes; las ampliaciones legalmente permitidas deben comunicarse y justificarse dentro de ese plazo.</p>
    <p>También puedes reclamar ante la autoridad de protección de datos competente, en particular la de tu residencia habitual, lugar de trabajo o lugar de la presunta infracción. Consulta el <a href="https://www.edpb.europa.eu/about-edpb/about-edpb/members_en" rel="noreferrer">directorio de autoridades europeas</a>.</p>
    <h2>7. Cookies, decisiones automatizadas y menores</h2>
    <p>La aplicación utiliza cookies técnicas de sesión y seguridad. Cloudflare puede añadir cookies de protección según los servicios habilitados. No utiliza cookies opcionales de analítica o publicidad. Consulta la <a href="{{ route('cookies') }}" wire:navigate>política de cookies</a>.</p>
    <p>El formulario del sitio no realiza perfiles ni toma decisiones automatizadas con efectos jurídicos. Las funciones de IA descritas en las páginas de producto no se ejecutan sobre los visitantes de este sitio. El sitio está dirigido a clientes empresariales y no ofrece servicios orientados a menores.</p>
    <h2>8. Cambios y alcance de esta versión</h2>
    <p>La fecha del documento se actualizará cuando cambie el tratamiento descrito. Los cambios relevantes deben informarse antes de aplicarse. Esta política no constituye una certificación de cumplimiento del RGPD. Su alcance incluye el sitio, las cuentas y las consultas preliminares de ciberseguridad; no sustituye los acuerdos de tratamiento de los servicios contratados.</p>
@endsection
